In [2]:
import gym
import numpy as np

# Create the FrozenLake environment
env = gym.make('FrozenLake-v1')

# Set the parameters
num_episodes = 10000
learning_rate = 0.1
discount_factor = 0.99
epsilon = 0.1

# Initialize the Q-table
state_space = env.observation_space.n
action_space = env.action_space.n
q_table = np.zeros((state_space, action_space))

# Function to choose an action based on epsilon-greedy strategy
def choose_action(state):
    if np.random.uniform(0, 1) < epsilon:
        # Explore: Choose a random action
        return env.action_space.sample()
    else:
        # Exploit: Choose the action with the highest Q-value
        return np.argmax(q_table[state, :])

# SARSA algorithm
for episode in range(num_episodes):
    state = env.reset()
    action = choose_action(state)
    done = False

    while not done:
        next_state, reward, done, _ = env.step(action)
        next_action = choose_action(next_state)

        # Update the Q-table using the SARSA update rule
        q_table[state, action] += learning_rate * (
                reward + discount_factor * q_table[next_state, next_action] - q_table[state, action])

        state = next_state
        action = next_action

# Print the learned Q-table
print(q_table)

# Close the environment
env.close()


/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


[[0.24499386 0.22780564 0.22887017 0.22295258]
 [0.12371505 0.13193191 0.13893144 0.21043981]
 [0.22048782 0.18351757 0.17914378 0.18247866]
 [0.13273611 0.11067872 0.09951371 0.17347632]
 [0.27672594 0.20461735 0.12695699 0.09834951]
 [0.         0.         0.         0.        ]
 [0.25032858 0.11290035 0.11520803 0.05844781]
 [0.         0.         0.         0.        ]
 [0.17015976 0.22403019 0.26150006 0.3130842 ]
 [0.27925082 0.39987753 0.26224562 0.23145163]
 [0.53664619 0.36836008 0.30237019 0.26235564]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.35190928 0.28420828 0.46610933 0.42094468]
 [0.57218234 0.71668594 0.6832924  0.60694771]
 [0.         0.         0.         0.        ]]


In [14]:
import gym
import numpy as np

env=gym.make('FrozenLake-v1')

epsilon=0.1
alpha=0.1
episodes=10000
discount_factor=0.99

state_space=env.observation_space.n
action_space=env.action_space.n
q_table=np.zeros((state_space,action_space))


def choose_action(state):
  if np.random.uniform(0,1)<epsilon:
      return env.action_space.sample()

  else:
      return np.argmax(q_table[state,:])


for episode in range(episodes):
  state=env.reset()
  done=False
  action=choose_action(state)

  while not done:
    
    new_state,reward,done,_=env.step(action)
    next_action=choose_action(new_state)

    q_table[state,action]+=alpha*(reward+discount_factor*q_table[new_state,next_action]-q_table[state,action])

    state=new_state
    action=next_action

print(q_table)

env.close()



[[0.37138547 0.33082017 0.33505441 0.31308459]
 [0.17612233 0.16646817 0.17358049 0.28861712]
 [0.23502982 0.17206908 0.14705498 0.16744434]
 [0.12954693 0.00904905 0.         0.00117823]
 [0.41477323 0.26854221 0.30240712 0.19181916]
 [0.         0.         0.         0.        ]
 [0.14615186 0.23189741 0.12662986 0.0660602 ]
 [0.         0.         0.         0.        ]
 [0.2788914  0.30305724 0.30974364 0.45726182]
 [0.27153414 0.55436743 0.39370523 0.33674984]
 [0.57472091 0.43229217 0.40131662 0.2424928 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.3333029  0.56180558 0.64691909 0.25584236]
 [0.6016216  0.83573275 0.73392463 0.6214035 ]
 [0.         0.         0.         0.        ]]
